import imgUrl from '../../../src/assets/img/layer-switcher/image.png';
import vecUrl from '../../../src/assets/img/layer-switcher/vec.png';
import terUrl from '../../../src/assets/img/layer-switcher/ter.png';
import img3dUrl from '../../../src/assets/img/layer-switcher/image-3d.png';

export const defaultOptions = [
  {
    type: 'map',
    defaultShow: 'dzdt',
    thumbnailUrl: '',
    children: [
      {
        id: 'yxdt',
        label: '影像',
        thumbnailUrl: imgUrl,
        children: [
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1492,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 2,
            geotype: 'polygon',
            label: '全球境界',
            sort: 1504,
            highParamInfo: [],
            type: 'tdt',
            url: 'http://t1.tianditu.gov.cn/ibo_w/wmts?tk=0c4bf211134dd7fce45d5be020eb7de7',
            visibleLayers: ['ibo'],
            parentName: '基础地图',
            layerTag: 'ibo_w',
            selectLayer: 'bou',
            name: '全球境界',
            initChecked: false,
            id: 'f2j6g46e-82ab-3c7c-7520-417c8l7h4098',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          },
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1489,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 1,
            geotype: 'polygon',
            label: '影像注记',
            sort: 1501,
            highParamInfo: [],
            type: 'tdt',
            url: 'http://t1.tianditu.gov.cn/cia_w/wmts?tk=0c4bf211134dd7fce45d5be020eb7de7',
            visibleLayers: ['cia'],
            parentName: '基础地图',
            layerTag: 'cia_w',
            selectLayer: 'cia',
            name: '影像注记',
            initChecked: false,
            id: '2053ce67-7835-d7a2-23c5-617c834ace7e',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          },
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1078,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 0,
            geotype: 'polygon',
            label: '天地图影像',
            sort: 1129,
            type: 'tdt',
            url: 'http://t0.tianditu.gov.cn/img_w/wmts?tk=0c4bf211134dd7fce45d5be020eb7de7',
            visibleLayers: ['img'],
            parentName: '基础地图',
            layerTag: 'img_w',
            selectLayer: 'img',
            name: '天地图影像',
            initChecked: false,
            id: '424b97f9-5040-0ef2-8ea7-c17aaek7j5c2',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          }
        ]
      },
      {
        id: 'dzdt',
        label: '电子地图',
        thumbnailUrl: vecUrl,
        children: [
          {
            parent: 'c422cb5b645e41608d2af078959d6587',
            layerDesc: '图层介绍',
            showIndex: 1486,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 1,
            geotype: 'polygon',
            label: '电子地图注记',
            sort: 1498,
            highParamInfo: [],
            type: 'tdt',
            url: 'http://t0.tianditu.gov.cn/cva_w/wmts?tk=17d1619c13e4508bc1945bd59de4edf8',
            visibleLayers: ['cva'],
            parentName: '资源目录',
            layerTag: 'zhuji',
            selectLayer: 'vec',
            name: '电子地图注记',
            initChecked: false,
            id: '35f38315-c80e-cf6a-683b-917c82b67a71',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          },
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1396,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 0,
            geotype: 'polygon',
            label: '电子地图',
            sort: 1432,
            highParamInfo: [],
            type: 'tdt',
            url: 'http://t1.tianditu.com/vec_w/wmts?tk=5f6be52182d36a123d68995e0c8fc8fa',
            visibleLayers: ['vec'],
            parentName: '基础地图',
            layerTag: 'wewerwer',
            selectLayer: 'vec',
            name: '电子地图',
            initChecked: false,
            id: 'f8d3717c-e84d-1f5c-b8af-b17c2f319b5f',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          }
        ]
      }
    ]
  },
  {
    type: 'earth',
    defaultShow: 'yxdt2',
    terrainDefaultShow: false,
    thumbnailUrl: '',
    children: [
      {
        id: 'yxdt2',
        label: '影像',
        thumbnailUrl: img3dUrl,
        children: [
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1492,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 3,
            geotype: 'polygon',
            label: '全球境界',
            sort: 1504,
            highParamInfo: [],
            type: 'tdt',
            url: 'http://t1.tianditu.gov.cn/ibo_w/wmts?tk=0c4bf211134dd7fce45d5be020eb7de7',
            visibleLayers: ['ibo'],
            parentName: '基础地图',
            layerTag: 'ibo_w',
            selectLayer: 'bou',
            name: '全球境界',
            initChecked: false,
            id: 'f27d856e-82ab-3c7c-7520-417c83593098',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          },
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1489,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 2,
            geotype: 'polygon',
            label: '影像注记',
            sort: 1501,
            highParamInfo: [],
            type: 'tdt',
            url: 'http://t1.tianditu.gov.cn/cia_w/wmts?tk=0c4bf211134dd7fce45d5be020eb7de7',
            visibleLayers: ['cia'],
            parentName: '基础地图',
            layerTag: 'cia_w',
            selectLayer: 'cia',
            name: '影像注记',
            initChecked: false,
            id: '0lj7ce67-7835-d7a2-23c5-61790kyace7e',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          },
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1078,
            serverOrigin: 'other',
            identifyField: [],
            mapIndex: 1,
            geotype: 'polygon',
            label: '天地图影像',
            sort: 1129,
            type: 'tdt',
            url: 'http://t0.tianditu.gov.cn/img_w/wmts?tk=0c4bf211134dd7fce45d5be020eb7de7',
            visibleLayers: ['img'],
            parentName: '基础地图',
            layerTag: 'img_w',
            selectLayer: 'img',
            name: '天地图影像',
            initChecked: false,
            id: '424b97f9-5040-0ef2-8ea7-c17aae36bec2',
            opacity: 1,
            tp: 'layer',
            group: '1',
            isBaseMapLayer: true,
            isDefault: true
          },
          {
            parent: '1352ea0a-d327-bc06-0dc4-917aae367eb1',
            layerDesc: '图层介绍',
            showIndex: 1539,
            serverOrigin: 'arcgis',
            identifyField: [],
            mapIndex: 0,
            geotype: 'polygon',
            label: 'ESRI影像',
            sort: 1545,
            highParamInfo: [],
            type: 'wmts',
            url: 'https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/WMTS',
            visibleLayers: [],
            parentName: '基础地图',
            layerTag: 'esri',
            initChecked: false,
            id: 'bcf7f24d-6921-6396-7939-517cc4dbc290',
            opacity: 1,
            tp: 'layer',
            group: '1',
            name: 'ESRI影像',
            isBaseMapLayer: true,
            isDefault: false
          }
        ]
      },
      {
        id: '3123456',
        label: '地形',
        type: 'terrain',
        underGround: true,
        thumbnailUrl: terUrl,
        children: [
          {
            parent: 'c422cb5b645e41608d2af078959d6587',
            layerDesc: '图层介绍',
            showIndex: 1421,
            serverOrigin: '3d_server',
            identifyField: [],
            mapIndex: 0,
            geotype: 'polygon',
            label: '中国地形',
            sort: 1469,
            highParamInfo: [],
            type: 'terrain',
            url: 'https://tiles1.geovisearth.com/base/v1/terrain/?token=bf8ba5378204f15b28d2650605c3151751863775c86ed9f1fd97047cc07d70af',
            visibleLayers: [''],
            parentName: '',
            layerTag: 'dixing',
            selectLayer: '',
            initChecked: false,
            id: 'a6719ec3-d97e-7a97-5fca-217c773f0de33123456',
            opacity: 1,
            tp: 'layer',
            group: '1',
            name: '中国地形',
            isBaseMapLayer: true,
            isDefault: true
          }
        ]
      }
    ]
  }
];
