/* Automatically generated by './build/bin/build-entry.js' */

import Map from '../packages/map/index.js';
import ConfigProvider from '../packages/config-provider/index.js';
import LayerSwitcher from '../packages/layer-switcher/index.js';
import Earth from '../packages/earth/index.js';
import MapEarth from '../packages/map-earth/index.js';
import LayerManager from '../packages/layer-manager/index.js';
import IdentifyPopup from '../packages/identify-popup/index.js';
import DrawTool3d from '../packages/draw-tool3d/index.js';
import DrawTool from '../packages/draw-tool/index.js';
import BubbleLayer from '../packages/bubble-layer/index.js';
import ClusterLayer from '../packages/cluster-layer/index.js';
import HeatmapLayer from '../packages/heatmap-layer/index.js';
import HighchartsLayer from '../packages/highcharts-layer/index.js';
import ScatterLayer from '../packages/scatter-layer/index.js';
import MasspointLayer from '../packages/masspoint-layer/index.js';
import MarkersLayer from '../packages/markers-layer/index.js';
import MigrateLayer from '../packages/migrate-layer/index.js';
import Navigate from '../packages/navigate/index.js';
import MapMeasure from '../packages/map-measure/index.js';
import FileImport from '../packages/file-import/index.js';
import FileExport from '../packages/file-export/index.js';
import Legend from '../packages/legend/index.js';
import ExportMap from '../packages/export-map/index.js';
import BookMark3d from '../packages/book-mark3d/index.js';
import Roam3d from '../packages/roam3d/index.js';
import SelectTool from '../packages/select-tool/index.js';
import IconSvg from '../packages/icon-svg/index.js';
import SaveTool from '../packages/save-tool/index.js';
import DeleteTool from '../packages/delete-tool/index.js';
import GeneralButton from '../packages/general-button/index.js';
import SpatialAnalysis3d from '../packages/spatial-analysis3d/index.js';
import GeneralCard from '../packages/general-card/index.js';
import MapMeasure3d from '../packages/map-measure3d/index.js';
import SchemeLayer from '../packages/scheme-layer/index.js';
import SceneSplit3d from '../packages/scene-split3d/index.js';
import ClipTools from '../packages/clip-tools/index.js';
import FlattenTools from '../packages/flatten-tools/index.js';
import BaseControl3d from '../packages/base-control3d/index.js';
import PlotTool from '../packages/plot-tool/index.js';
import FullFigure from '../packages/full-figure/index.js';
import ToolBar from '../packages/tool-bar/index.js';
import CopyTool from '../packages/copy-tool/index.js';
import PasteTool from '../packages/paste-tool/index.js';
import SplitTool from '../packages/split-tool/index.js';
import UnionTool from '../packages/union-tool/index.js';
import PlaceSearch from '../packages/place-search/index.js';
import GeneralMask from '../packages/general-mask/index.js';
import CuttingLayer from '../packages/cutting-layer/index.js';
import LayerStyle from '../packages/layer-style/index.js';
import GeneralBar from '../packages/general-bar/index.js';
import MapShare from '../packages/map-share/index.js';
import Annotation from '../packages/annotation/index.js';
import EarthVideo from '../packages/earth-video/index.js';
import MapLabel from '../packages/map-label/index.js';
import EditTool from '../packages/edit-tool/index.js';
import SceneSplit from '../packages/scene-split/index.js';
import HawkEye from '../packages/hawk-eye/index.js';
import RollerBlind from '../packages/roller-blind/index.js';
import FullScreen from '../packages/full-screen/index.js';
const components = [
  Map,
  ConfigProvider,
  LayerSwitcher,
  Earth,
  MapEarth,
  LayerManager,
  IdentifyPopup,
  DrawTool3d,
  DrawTool,
  BubbleLayer,
  ClusterLayer,
  HeatmapLayer,
  HighchartsLayer,
  ScatterLayer,
  MasspointLayer,
  MarkersLayer,
  MigrateLayer,
  Navigate,
  MapMeasure,
  FileImport,
  FileExport,
  Legend,
  ExportMap,
  BookMark3d,
  Roam3d,
  SelectTool,
  IconSvg,
  SaveTool,
  DeleteTool,
  GeneralButton,
  SpatialAnalysis3d,
  GeneralCard,
  MapMeasure3d,
  SchemeLayer,
  SceneSplit3d,
  ClipTools,
  FlattenTools,
  BaseControl3d,
  PlotTool,
  FullFigure,
  ToolBar,
  CopyTool,
  PasteTool,
  SplitTool,
  UnionTool,
  PlaceSearch,
  GeneralMask,
  CuttingLayer,
  LayerStyle,
  GeneralBar,
  MapShare,
  Annotation,
  EarthVideo,
  MapLabel,
  EditTool,
  SceneSplit,
  HawkEye,
  RollerBlind,
  FullScreen
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.1.0-2',
  install,
  Map,
  ConfigProvider,
  LayerSwitcher,
  Earth,
  MapEarth,
  LayerManager,
  IdentifyPopup,
  DrawTool3d,
  DrawTool,
  BubbleLayer,
  ClusterLayer,
  HeatmapLayer,
  HighchartsLayer,
  ScatterLayer,
  MasspointLayer,
  MarkersLayer,
  MigrateLayer,
  Navigate,
  MapMeasure,
  FileImport,
  FileExport,
  Legend,
  ExportMap,
  BookMark3d,
  Roam3d,
  SelectTool,
  IconSvg,
  SaveTool,
  DeleteTool,
  GeneralButton,
  SpatialAnalysis3d,
  GeneralCard,
  MapMeasure3d,
  SchemeLayer,
  SceneSplit3d,
  ClipTools,
  FlattenTools,
  BaseControl3d,
  PlotTool,
  FullFigure,
  ToolBar,
  CopyTool,
  PasteTool,
  SplitTool,
  UnionTool,
  PlaceSearch,
  GeneralMask,
  CuttingLayer,
  LayerStyle,
  GeneralBar,
  MapShare,
  Annotation,
  EarthVideo,
  MapLabel,
  EditTool,
  SceneSplit,
  HawkEye,
  RollerBlind,
  FullScreen
};
